package vmmgo

const (
	VMMDLL_MAP_VAD_VERSION            = 6
	VMMDLL_MAP_VADEX_VERSION          = 3
	VMMDLL_MAP_MODULE_VERSION         = 6
	VMMDLL_MAP_UNLOADEDMODULE_VERSION = 2
	VMMDLL_MAP_EAT_VERSION            = 2
	VMMDLL_MAP_IAT_VERSION            = 2
	VMMDLL_MAP_HEAP_VERSION           = 4
	VMMDLL_MAP_HEAPALLOC_VERSION      = 1
	VMMDLL_MAP_THREAD_VERSION         = 4
	VMMDLL_MAP_HANDLE_VERSION         = 2
	VMMDLL_MAP_POOL_VERSION           = 2
	VMMDLL_MAP_NET_VERSION            = 3
	VMMDLL_MAP_PHYSMEM_VERSION        = 2
	VMMDLL_MAP_USER_VERSION           = 2
	VMMDLL_MAP_SERVICE_VERSION        = 3
)
